name: Build Project

on:
    push:
    workflow_dispatch:

jobs:
  build:
    name: ${{matrix.platform.name}} ${{matrix.config}}
    runs-on: ${{matrix.platform.os}}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows VS2022, os: windows-2022  }
        - { name: Linux GCC,      os: ubuntu-latest }
        # Doesn't support flags
        # - { name: Linux Clang,    os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        - { name: macOS,          os: macos-latest  }
        config: [Debug, Release]

    steps:
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev
      
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
    
      - name: Build Project
        shell: bash
        run: python build.py build ${{matrix.config}} && python build.py build ${{matrix.config}} Shared
        
      # - name: Upload built EXE file
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ github.event.repository.name }}-${{ matrix.config }}
      #     path: bin/${{ matrix.config }}-windows-x86_64/Pong.exe
